version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.60.0
    steps:
      - checkout
      - run: cargo fmt && cargo clippy -- -D warnings
      - run: cargo test && cargo build --release
      - run: mkdir release && cp target/release/cemtexer release/
      - run: curl -LO https://github.com/tcnksm/ghr/releases/download/v0.14.0/ghr_v0.14.0_linux_amd64.tar.gz && tar -xvf ghr_v0.14.0_linux_amd64.tar.gz
      - run: ./ghr_v0.14.0_linux_amd64/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v0.1.1 release/
workflows:
  version: 2
  build:
    jobs:
      - build